In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
df =pd.read_csv("dataset/xAPI-Edu-Data.csv")

In [28]:
df.head()

,gender,NationalITy,PlaceofBirth,StageID,GradeID,SectionID,Topic,Semester,Relation,raisedhands,VisITedResources,AnnouncementsView,Discussion,ParentAnsweringSurvey,ParentschoolSatisfaction,StudentAbsenceDays,Class
0,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,15,16,2,20,Yes,Good,Under-7,M
1,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,20,20,3,25,Yes,Good,Under-7,M
2,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,10,7,0,30,No,Bad,Above-7,L
3,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,30,25,5,35,No,Bad,Above-7,L
4,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,40,50,12,50,No,Bad,Above-7,M

In [29]:
df.tail()

,gender,NationalITy,PlaceofBirth,StageID,GradeID,SectionID,Topic,Semester,Relation,raisedhands,VisITedResources,AnnouncementsView,Discussion,ParentAnsweringSurvey,ParentschoolSatisfaction,StudentAbsenceDays,Class
475,F,Jordan,Jordan,MiddleSchool,G-08,A,Chemistry,S,Father,5,4,5,8,No,Bad,Above-7,L
476,F,Jordan,Jordan,MiddleSchool,G-08,A,Geology,F,Father,50,77,14,28,No,Bad,Under-7,M
477,F,Jordan,Jordan,MiddleSchool,G-08,A,Geology,S,Father,55,74,25,29,No,Bad,Under-7,M
478,F,Jordan,Jordan,MiddleSchool,G-08,A,History,F,Father,30,17,14,57,No,Bad,Above-7,L
479,F,Jordan,Jordan,MiddleSchool,G-08,A,History,S,Father,35,14,23,62,No,Bad,Above-7,L

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gender                    480 non-null    object
 1   NationalITy               480 non-null    object
 2   PlaceofBirth              480 non-null    object
 3   StageID                   480 non-null    object
 4   GradeID                   480 non-null    object
 5   SectionID                 480 non-null    object
 6   Topic                     480 non-null    object
 7   Semester                  480 non-null    object
 8   Relation                  480 non-null    object
 9   raisedhands               480 non-null    int64
 10  VisITedResources          480 non-null    int64
 11  AnnouncementsView         480 non-null    int64
 12  Discussion                480 non-null    int64
 13  ParentAnsweringSurvey     480 non-null    object
 14  ParentschoolSatisfaction  480 non-null    object
 15  StudentAbsenceDays        480 non-null    object
 16  Class                     480 non-null    object
dtypes: int64(4), object(13)
memory usage: 63.9+ KB

In [31]:
df.columns

Index(['gender', 'NationalITy', 'PlaceofBirth', 'StageID', 'GradeID',
       'SectionID', 'Topic', 'Semester', 'Relation', 'raisedhands',
       'VisITedResources', 'AnnouncementsView', 'Discussion',
       'ParentAnsweringSurvey', 'ParentschoolSatisfaction',
       'StudentAbsenceDays', 'Class'],
      dtype='object')

In [32]:
for col in df.columns:
    print(col,":",df[col].unique())

gender : ['M' 'F']
NationalITy : ['KW' 'lebanon' 'Egypt' 'SaudiArabia' 'USA' 'Jordan' 'venzuela' 'Iran'
 'Tunis' 'Morocco' 'Syria' 'Palestine' 'Iraq' 'Lybia']
PlaceofBirth : ['KuwaIT' 'lebanon' 'Egypt' 'SaudiArabia' 'USA' 'Jordan' 'venzuela' 'Iran'
 'Tunis' 'Morocco' 'Syria' 'Iraq' 'Palestine' 'Lybia']
StageID : ['lowerlevel' 'MiddleSchool' 'HighSchool']
GradeID : ['G-04' 'G-07' 'G-08' 'G-06' 'G-05' 'G-09' 'G-12' 'G-11' 'G-10' 'G-02']
SectionID : ['A' 'B' 'C']
Topic : ['IT' 'Math' 'Arabic' 'Science' 'English' 'Quran' 'Spanish' 'French'
 'History' 'Biology' 'Chemistry' 'Geology']
Semester : ['F' 'S']
Relation : ['Father' 'Mum']
raisedhands : [ 15  20  10  30  40  42  35  50  12  70  19   5  62  36  55  69  60   2
   0   8  25  75   4  45  14  33   7  13  29  39  49  16  28  27  21  80
  17  65  22  11   1   3 100   6  90  77  24  66  23  82  72  51  85  87
  95  81  53  92  83  67  96  57  73   9  32  52  59  61  79  18  74  97
  41  71  98  78  89  88  86  76  99  84]
VisITedResources : [16 20  7 25 50 30 12 10 21 80 88  6  1 14 70 40 13 15 60  0  2 19 85 90
  5 22 11 54 35 33  4 39 75 69  3  8 89 44 92 26 27 29 98  9 42 65 79 55
 63 91 51 58 68 82 72 52 62 71 66 43 95 31 41 81 61 83 84 17 94 48 86 74
 76 97 87 99 34 64 28 38 36 24 59 57 77 18 93 96 78]
AnnouncementsView : [ 2  3  0  5 12 13 15 16 25 30 19 44 22 20 35 36 40 33  4 52 50 10  9  8
 17 26 37  7 28  1 39  6 32 70 18 23 11 29 49 55 38 41 51 95 85 71 98 73
 48 58 93 83 53 63 62 82 72 42 46 77 21 88 66 86 80 56 91 65 76 24 74 59
 79 34 69 89 31 60 54 57 64 87 75 67 43 45 14 78]
Discussion : [20 25 30 35 50 70 17 22 80 12 11 19 60 66 90 96 99 40 33 43 16  4 88 77
 75  1  5  2  8 13 44  9 55 10 15  7  3 14 69 59 89 41 91 49 73 23 53 93
 51 83 24 84 61 94 34 81 29 46 26  6 76 86 85 65 95 64 32 37 36 27 39 74
 79 21 31 28 38 48 97 98 63 72 82 71 45 68 92 58 57 62]
ParentAnsweringSurvey : ['Yes' 'No']
ParentschoolSatisfaction : ['Good' 'Bad']
StudentAbsenceDays : ['Under-7' 'Above-7']
Class : ['M' 'L' 'H']

In [33]:
# 1. GradeID Temizliği
df['GradeID'] = df['GradeID'].str.replace('G-', '').astype(int)

# 2. Manuel Mapping (Binary ve Ordinal)
df['gender'] = df['gender'].map({'M': 1, 'F': 0})
df['Semester'] = df['Semester'].map({'S': 1, 'F': 0})
df['Relation'] = df['Relation'].map({'Mum': 1, 'Father': 0})
df['ParentAnsweringSurvey'] = df['ParentAnsweringSurvey'].map({'Yes': 1, 'No': 0})
df['ParentschoolSatisfaction'] = df['ParentschoolSatisfaction'].map({'Good': 1, 'Bad': 0})
df['StudentAbsenceDays'] = df['StudentAbsenceDays'].map({'Above-7': 1, 'Under-7': 0})
df['SectionID'] = df['SectionID'].map({'A': 0, 'B': 1, 'C': 2})


df['StageID'] = df['StageID'].str.strip().map({'lowerlevel': 0, 'MiddleSchool': 1, 'HighSchool': 2})

# Hedef Değişken (Class)
df['Class'] = df['Class'].map({'L': 0, 'M': 1, 'H': 2})

# 3. Yeni Özellik Oluşturma 

df['is_displaced'] = (df['NationalITy'] != df['PlaceofBirth']).astype(int)


df.drop(['NationalITy', 'PlaceofBirth'], axis=1, inplace=True)

In [34]:
df = pd.get_dummies(df, columns=['Topic'], drop_first=True)

In [35]:
from sklearn.model_selection import train_test_split

X = df.drop('Class', axis=1)
y = df['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


print(X_train.info())

<class 'pandas.core.frame.DataFrame'>
Index: 384 entries, 132 to 102
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gender                    384 non-null    int64
 1   StageID                   384 non-null    int64
 2   GradeID                   384 non-null    int64
 3   SectionID                 384 non-null    int64
 4   Semester                  384 non-null    int64
 5   Relation                  384 non-null    int64
 6   raisedhands               384 non-null    int64
 7   VisITedResources          384 non-null    int64
 8   AnnouncementsView         384 non-null    int64
 9   Discussion                384 non-null    int64
 10  ParentAnsweringSurvey     384 non-null    int64
 11  ParentschoolSatisfaction  384 non-null    int64
 12  StudentAbsenceDays        384 non-null    int64
 13  is_displaced              384 non-null    int64
 14  Topic_Biology             384 non-null    bool
 15  Topic_Chemistry           384 non-null    bool
 16  Topic_English             384 non-null    bool
 17  Topic_French              384 non-null    bool
 18  Topic_Geology             384 non-null    bool
 19  Topic_History             384 non-null    bool
 20  Topic_IT                  384 non-null    bool
 21  Topic_Math                384 non-null    bool
 22  Topic_Quran               384 non-null    bool
 23  Topic_Science             384 non-null    bool
 24  Topic_Spanish             384 non-null    bool
dtypes: bool(11), int64(14)
memory usage: 49.1 KB
None

In [36]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Modeli Tanımla

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# 2. Modeli Eğit 
rf_model.fit(X_train, y_train)

# 3. Tahmin Yap 
y_pred = rf_model.predict(X_test)

# 4. Sonuçları Görüntüle
print(f"Model Doğruluk Oranı (Accuracy): %{accuracy_score(y_test, y_pred)*100:.2f}")
print("\nSınıflandırma Raporu:\n", classification_report(y_test, y_pred))

Model Doğruluk Oranı (Accuracy): %85.42

Sınıflandırma Raporu:
               precision    recall  f1-score   support

           0       0.89      0.96      0.93        26
           1       0.85      0.85      0.85        48
           2       0.80      0.73      0.76        22

    accuracy                           0.85        96
   macro avg       0.85      0.85      0.85        96
weighted avg       0.85      0.85      0.85        96